use EXPENSES
go

SELECT * FROM TB_USUARIOS

SELECT * FROM TB_VIGENCIA

INSERT INTO TB_VIGENCIA (VIG_DATAINICIO,VIG_DATAFINAL,VIG_USUCODIGO)
	   VALUES (CONVERT(smalldatetime,'01/04/2018',103),CONVERT(smalldatetime,'30/04/2018',103),1)